### ISSUE TITLE
[shaped-scripts] shaped-import-spell: single spell limitation?

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#10]
I am not sure if this is a bug or design limitation, but currently it seems you can only import one spell at a time, trying to add more than one using a comma separated list generates an error:

(From ShapedScripts): An error occurred: Unrecognised or poorly formed option [$$$]
ShapedScripts: magic missile,shield

Also the need to have the sheet open and press the "import" button seems like an odd usability issue, however I suspect this may be due to the limitation of sheetworkers vs. api.

**Comment by symposion** [comment]
Sorry, poor documentation. Thanks to the way that I do option switches, multiple spells should be imported with a -- before each one:

!shaped-import-spell --magic missile --shield

Will update the forum post to reflect this

**Comment by symposion** [comment]
Ok, forum post updated, closing for the moment. Obviously lots more proper documentation needed!
