### ISSUE TITLE
shaped-import-statblock:  CR 

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#12]
If you import a monster that is a 1/4 CR, this actually appears in the statblock as 0.25, rather than the literal 1/4.  Also the XP didn't import properly.

Example statblock:
Aarakocra
Medium humanoid (aarakocra), neutral good
Armor Class 12
Hit Points 13 (3d8)
Speed 20 ft. , fly 50 ft.
STR
10 (+0)
DEX
14 (+2)
CON
10 (+0)
INT
11 (+0)
WIS
12 (+1 )
CHA
11 (+0)
Skills Perception +5
Senses passive Perception 15
Languages Auran
Challenge 1/4 (50 XP)
Dive Attack. If the aarakocra is flying and dives at least 30 feet
straight toward a target and then hits it with a melee weapon
attack, the attack dea ls an extra 3 (1d6) damage to the target.
ACTIONS
Talon. Melee Weapon Attack: +4 to hit, reach 5 ft. , one target.
Hit: 4 (ld4 + 2) slash ing damage.
javelin. Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or
ra nge 30/120 ft ., one target. Hit: 5 (1d6 + 2) piercing damage.

**Comment by symposion** [comment]
This is actually a problem with the sheet that I need to take up with Mark. I think that the sheet doesn't handle fractional CRs properly - which is why I made it a decimal instead - but I think even that isn't quite right. I'll chat to Mark when I get a moment to see if we can sort it out.

**Comment by symposion** [comment]
Ok, this is fixed in the latest version
