### ISSUE TITLE
shaped-import-monster:  Name Normalization

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#13]
Often pulling stat blocks will end up with names in all caps (example added to the end), but it would be nice to normalize this name on import if possible:

ANIMATED ARMOR
Medium construct, unaligned
Armor Class 18 (natural armor)
Hit Points 33 (6d8 + 6)
Speed 25ft.
STR
14 (+2)
DEX
11 (+0)
CON
13 (+1)
INT
1 (-5)
WIS
3 (-4)
CHA
1 (-5)
Damage Immunities poison, psychic
Condition Immunities blinded, charmed, deafened, exhaustion,
frightened, paralyzed, petrified, poisoned
Senses blindsight 60ft. (blind beyond th is radius),
passive Perception 6
Languages -
Challenge 1 (200 XP)
Antimagic Susceptibility. The armor is incapacitated while in
the area of an anti magic field. If targeted by dispel magic, the
armor must succeed on a Constitution saving throw against the
caster's spell save DC or fall unconscious for 1 minute.
False Appearance. While the armor remains motion less, it is
indistinguishable from a normal suit of armor.
ACTIONS
Multiattack. The armor makes two melee attacks.
Slam. Melee Weapon Attack: +4 to hit, reach 5 ft ., one target.
Hit: 5 (ld6 + 2) bludgeoning damage.

**Comment by symposion** [comment]
Yeah, point taken. I'm going to refactor the code slightly to separate out the pure parsing from the text validation/transformation so that I can apply some of the same transforms to the monster JSON.

**Comment by symposion** [comment]
Fixed in latest version
