### ISSUE TITLE
[shaped-scripts] autoAmmo config cannot be set to false

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#31]
Running the following command:
!shaped-config --newCharSettings.autoAmmo false

Generates the following error:
"ShapedScripts 1459452100680 ERROR : Error: Invalid value [false] for option [newCharSettings.autoAmmo]"

**Comment by beeke01** [comment]
Note, setting to true works perfectly and quickly looking at the script I can't see a reason why it would fail with a false setting.

**Comment by symposion** [comment]
D'oh. Sloppy checking of a value using !!value when the option can validly have a falsey value.
