### ISSUE TITLE
[shaped-scripts] --rollHPOnDrop is not seen as a valid option

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#32]
Attempting to run the following command fails:
!shaped-config --rollHPOnDrop true

Following Error:
"ShapedScripts 1459452755732 ERROR : Error: Unrecognised or poorly formed option rollHPOnDrop true"

**Comment by symposion** [comment]
D'oh. Sloppy checking of a value using !!value when the option can validly have a falsey value.

**Comment by symposion** [comment]
Urk. I don't really like my config code - the sooner I can steal Aaron's code the better. I'd defined the default but not the validator - they're defined in separate places so it's easy to miss.
