### ISSUE TITLE
[shaped-scripts] Automatically Rolling HP no longer works

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#33]
I currently have the following configuration set (unimified for readability):
{
    "logLevel":"INFO",
    "tokenSettings": {
        "number":true,
        "bar1": {
            "attribute": "", "max": false, "link": false, "showPlayers": false
        }
        ,
        "bar2": {
            "attribute": "AC", "max": false, "link": false, "showPlayers": false
        }
        ,
        "bar3": {
            "attribute": "HP", "max": true, "link": true, "showPlayers": false
        }
        ,
        "showName":true,
        "showNameToPlayers":false
    }
    ,
    "newCharSettings": {
        "sheetOutput": "output_to_gm", "deathSaveOutput": "output_to_gm", "initiativeOutput": "output_to_gm", "showNameOnRollTemplate": "show_character_name_yes", "rollOptions": "roll_1", "initiativeRoll": "normal_initiative", "initiativeToTracker": "initiative_to_tracker_yes", "breakInitiativeTies": "initiative_tie_breaker_var", "showTargetAC": "attacks_vs_target_ac_no", "showTargetName": "attacks_vs_target_name_no", "autoAmmo": "ammo_auto_use_var"
    }
    ,
    "rollHPOnDrop":true
}

Even though rollHPOnDrop is true, I can't seem to get any token to automatically roll HP.  I made sure to set bar3 to HP trying both true and false for the the bar3 link.  Regardless of the above configuration, I did make sure that the tokens bar3 was not linked (just default hp values set), but it still did not roll HP.

**Comment by symposion** [comment]
This was fixed in 0.2.1
