### ISSUE TITLE
[shaped-scripts] Auto-decrement spell slots

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-api-scripts#45]
Decrement spell slots on cast
* Output list of available slots after each cast - ideally should use something from the sheet

**Comment by Brunhine** [comment]
I think the remaining slots output would be best executed by the sheet in
the same way that ammo is done. For consistency's sake.

**Comment by symposion** [comment]
>I think the remaining slots output would be best executed by the sheet in
>the same way that ammo is done. For consistency's sake.

Agreed, that was how i thought it would work. I mentioned to Mark about making the "Spell Slots" text clickable on the sheet to output the remaining slots, and we could then call this sheet roll to output the information. I seem to remember he was up for that idea, so you could drop him a note and ask about it.

**Comment by symposion** [comment]
This issue was moved to symposion/roll20-shaped-scripts#16
