### ISSUE TITLE
Support comma-separated spells and monsters on CLI

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-api-scripts#49]

**Comment by Brunhine** [comment]
I see the stated timesaving potential in this, but what if I make an npc with the name "Lord Tyrone, keeper of the pit"?

**Comment by symposion** [comment]
I'll try matching against the full string first and then split afterwards if that fails

**Comment by Brunhine** [comment]
devils advocate here:

Beholder,Lord Tyrone, keeper of the pit,Lich

**Comment by symposion** [comment]
Well, sh*t, it looks like it just isn't your day then. :-)
I share your distaste for the lack of rigour in it, which is part of the reason why i didn't do it originally, but:
a) there's an easy workaround in this case
b) it's a rare case
c) it does have appreciable utility most of the time

**Comment by symposion** [comment]
(also:
d) It was Kryx's script originally and he probably deserves a chance to shoehorn a few privileged features ;-)
)
