### ISSUE TITLE
Integrate Kevin's Advantage Tracker

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-api-scripts#55]

**Comment by Brunhine** [comment]
Basic functionality has been coded. Includes:

- Ability to set rolltype via `!shaped-at` command
 - accepts either `--advantage` `--disadvantage` or `--normal`
- Updated the associated token with the green status marker for advantage, or red for disadvantage

Still to do:
- Update a newly placed token with the appropriate status marker if rolltype is not `normal`

Want to do:
- Create a new config option that would allow for adv/dis to be set with a 'revert' flag that would revert the rolltype back to normal (or whatever it was before) after a roll is made.
