### ISSUE TITLE
Auto-configure vision like the old script did

### ISSUE THREAD

**Issue by symposion** [symposion/roll20-api-scripts#68]
The old script would set up token vision based on the sense of the imported character. Kind of irrelevant since virtual all the tokens are going to be GM-controlled anyway, but I guess CTRL-L is a thing..

**Comment by Brunhine** [comment]
I can see the value in this. I use vision on my npcs to determine line of sight to things sometimes.

I will add this.

**Comment by symposion** [comment]
This issue was moved to symposion/roll20-shaped-scripts#15
