### ISSUE TITLE
Shaped Script Monster Stat Block - Error Message in Console

### ISSUE THREAD

**Issue by agjwilson** [symposion/roll20-api-scripts#86]
I've tried using the script for the first time. 
My error is ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."

The image is in my library. Character Sheet for this monster is empty. (Repeated twice with different tokens and monsters)

I was using the command !shaped-import-statblock

**Comment by Brunhine** [comment]
This sometimes happens, even though everything works. Did the import fail to execute in this case? 

This is an error sent by Roll20, and not the script btw.

**Comment by symposion** [comment]
This issue was moved to symposion/roll20-shaped-scripts#3
