### ISSUE TITLE
[shaped-scripts] shaped-import-spell - toggles on initial import

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#9]
Initial toggles are not properly setup upon spell import.  For example if you import the spell "fire bolt", it is an attack based cantrip, but the attack toggle is not checked.

**Comment by symposion** [comment]
Ah yes, I am aware of this, I need to chat to Mark about this to decide whether it's something that the sheetworkers can handle more elegantly, or whether I need to work around it in the script. In theory the sheetworkers should automatically toggle that on when I set values for the fields within the attack section, but that doesn't seem to be working ATM.

Thanks for reporting lots of helpful bugs!

**Comment by symposion** [comment]
Hey, I think I've fixed this now - unfortunately it requires an updated version of the spell json again - just waiting for Mark to merge the pull request and then I'll close this bug.

**Comment by symposion** [comment]
Ok, so with the latest data from Kryx's github and the latest script, this looks to be fixed. Let me know if you find any different.
