### ISSUE TITLE
[shaped-scripts] script crashes when linked token has no HP formula

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#92]
So I have spell effects that are linked to character sheets but the sheet is blank.  When I attempt to pull the spell effect template from the journal, it generates the following error then the API stops:

"Error: Unable to find attribute named hp_formula for character 5 ft. radius circle(-JJdCAhMpLnF1lATFyKB) in chat command."

**Comment by symposion** [comment]
This should be fixed in the latest version.
