### ISSUE TITLE
Damage checked on Multiattack when importing.

### ISSUE THREAD

**Issue by cynik6** [symposion/roll20-api-scripts#96]
Sheet version: 2.7.0
Script Version: v1.4.3 (latest?)

When importing any monster from the JSON files, things such as multiattack and legendary action legendary actions import with the damage block checked. When using the macros or directly from the sheet, those items roll damage.

**Comment by symposion** [comment]
Hi, this is a sheet issue, not a script issue. It happens when you import from the SRD as well. Have raised https://github.com/mlenser/roll20-character-sheets/issues/120 for you.

**Comment by symposion** [comment]
Sorry, the correct issue is https://github.com/mlenser/roll20-character-sheets/issues/96 - Mark already had it covered.
